chore: test generated files

diff --git a/.github/workflows/webapp.yml b/.github/workflows/webapp.yml
--- a/.github/workflows/webapp.yml
+++ b/.github/workflows/webapp.yml
@@ -59,7 +59,6 @@ jobs:
         uses: actions/checkout@v3
       - name: Get dependencies
         run: |
-          set -x # echo all executed commands to the terminal
           set -e # abort if any command fails
           sudo apt-get install -y npm
       - name: Check for style diffs
@@ -67,7 +66,7 @@ jobs:
         run: |
           set -x # echo all executed commands to the terminal
           set -e # abort if any command fails
-          npm --prefix web install
+          npm --prefix web ci
           npm --prefix web run lint:fix
           set +e # do not end the script if a cmd returns an exit code
           git diff --exit-code web > style.diff
@@ -118,6 +117,26 @@ jobs:
     needs: [ decide-what-jobs-to-run ]
     if: ${{ needs.decide-what-jobs-to-run.outputs.update-generated-files == 'true' }}
     steps:
-      - name: Make PR
         run: |
-          echo hello world
+          set -e # abort if any command fails
+          sudo apt-get install -y npm
+      - name: Get source
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 2 # >1 needed for merge base
+      - name: Generate webapp files
+        run: |
+          set -x # echo all executed commands to the terminal
+          set -e # abort if any command fails
+          npm --prefix web ci
+          npm --prefix web run lint:fix
+          npm --prefix web run build
+          git diff --exit-code --name-only
+      - name: Create pull request
+        uses: peter-evans/create-pull-request@v4
+        with:
+          commit-message: Update genereated webapp files
+          branch: update-webapp-files
+          delete-branch: true
+          title: Update genereated webapp files
+
